// <auto-generated />
using System;
using Auth.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auth.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250913223631_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Auth.Domain.Aggregates.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.Scope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Scopes");
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activated")
                        .HasColumnType("bit");

                    b.Property<bool>("Closed")
                        .HasColumnType("bit");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Kid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Version")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activated")
                        .HasColumnType("bit");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Auth.Domain.Entities.Authentication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authentication");
                });

            modelBuilder.Entity("Auth.Domain.Entities.Authorization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Authorization");
                });

            modelBuilder.Entity("Auth.Domain.Entities.Entitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ScopeId");

                    b.ToTable("Entitlement");
                });

            modelBuilder.Entity("Auth.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("Auth.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("Auth.Domain.Entities.ScopePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("bigint");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("ScopeId");

                    b.ToTable("ScopePermission");
                });

            modelBuilder.Entity("Auth.Persistence.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("LockedAt")
                        .HasColumnType("bigint");

                    b.Property<long?>("LockedUntil")
                        .HasColumnType("bigint");

                    b.Property<int>("Locktime")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Processed")
                        .HasColumnType("bit");

                    b.Property<Guid>("StreamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Outbox");
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.Scope", b =>
                {
                    b.OwnsOne("Auth.Domain.ValueObjects.Audience", "Audience", b1 =>
                        {
                            b1.Property<Guid>("ScopeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Audience");

                            b1.HasKey("ScopeId");

                            b1.ToTable("Scopes");

                            b1.WithOwner()
                                .HasForeignKey("ScopeId");
                        });

                    b.OwnsOne("Auth.Domain.ValueObjects.Action", "Action", b1 =>
                        {
                            b1.Property<Guid>("ScopeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Action");

                            b1.HasKey("ScopeId");

                            b1.ToTable("Scopes");

                            b1.WithOwner()
                                .HasForeignKey("ScopeId");
                        });

                    b.OwnsOne("Auth.Domain.ValueObjects.Resource", "Resource", b1 =>
                        {
                            b1.Property<Guid>("ScopeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Resource");

                            b1.HasKey("ScopeId");

                            b1.ToTable("Scopes");

                            b1.WithOwner()
                                .HasForeignKey("ScopeId");
                        });

                    b.Navigation("Action")
                        .IsRequired();

                    b.Navigation("Audience")
                        .IsRequired();

                    b.Navigation("Resource")
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.Session", b =>
                {
                    b.HasOne("Auth.Domain.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Auth.Domain.ValueObjects.Audience", "Audience", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Audience");

                            b1.HasKey("SessionId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsOne("Auth.Domain.ValueObjects.Device", "Device", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Device");

                            b1.HasKey("SessionId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.OwnsOne("Auth.Domain.ValueObjects.IpAddress", "IpAddress", b1 =>
                        {
                            b1.Property<Guid>("SessionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("IpAddress");

                            b1.HasKey("SessionId");

                            b1.ToTable("Sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId");
                        });

                    b.Navigation("Audience")
                        .IsRequired();

                    b.Navigation("Device")
                        .IsRequired();

                    b.Navigation("IpAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Entities.Authentication", b =>
                {
                    b.HasOne("Auth.Domain.Aggregates.User", null)
                        .WithOne("Authentication")
                        .HasForeignKey("Auth.Domain.Entities.Authentication", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Auth.Domain.ValueObjects.PasswordHash", "PasswordHash", b1 =>
                        {
                            b1.Property<Guid>("AuthenticationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PasswordHash");

                            b1.HasKey("AuthenticationId");

                            b1.ToTable("Authentication");

                            b1.WithOwner()
                                .HasForeignKey("AuthenticationId");
                        });

                    b.OwnsOne("Auth.Domain.ValueObjects.PendingPasswordHash", "PendingPasswordHash", b1 =>
                        {
                            b1.Property<Guid>("AuthenticationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Version")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PendingPasswordHashVersion");

                            b1.HasKey("AuthenticationId");

                            b1.ToTable("Authentication");

                            b1.WithOwner()
                                .HasForeignKey("AuthenticationId");

                            b1.OwnsOne("Auth.Domain.ValueObjects.PasswordHash", "PasswordHash", b2 =>
                                {
                                    b2.Property<Guid>("PendingPasswordHashAuthenticationId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("PendingPasswordHash");

                                    b2.HasKey("PendingPasswordHashAuthenticationId");

                                    b2.ToTable("Authentication");

                                    b2.WithOwner()
                                        .HasForeignKey("PendingPasswordHashAuthenticationId");
                                });

                            b1.Navigation("PasswordHash")
                                .IsRequired();
                        });

                    b.Navigation("PasswordHash")
                        .IsRequired();

                    b.Navigation("PendingPasswordHash");
                });

            modelBuilder.Entity("Auth.Domain.Entities.Authorization", b =>
                {
                    b.HasOne("Auth.Domain.Aggregates.User", null)
                        .WithOne("Authorization")
                        .HasForeignKey("Auth.Domain.Entities.Authorization", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Entities.Entitlement", b =>
                {
                    b.HasOne("Auth.Domain.Aggregates.Role", null)
                        .WithMany("Entitlements")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Aggregates.Scope", null)
                        .WithMany()
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Entities.Profile", b =>
                {
                    b.HasOne("Auth.Domain.Aggregates.User", null)
                        .WithOne("Profile")
                        .HasForeignKey("Auth.Domain.Entities.Profile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Auth.Domain.ValueObjects.EmailAddress", "EmailAddress", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("EmailAddress");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profile");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.OwnsOne("Auth.Domain.ValueObjects.PendingEmailAddress", "PendingEmailAddress", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsConfirmed")
                                .HasColumnType("bit")
                                .HasColumnName("PendingEmailAddressIsConfirmed");

                            b1.Property<Guid>("Version")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PendingEmailAddressVersion");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profile");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");

                            b1.OwnsOne("Auth.Domain.ValueObjects.EmailAddress", "EmailAddress", b2 =>
                                {
                                    b2.Property<Guid>("PendingEmailAddressProfileId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("PendingEmailAddress");

                                    b2.HasKey("PendingEmailAddressProfileId");

                                    b2.ToTable("Profile");

                                    b2.WithOwner()
                                        .HasForeignKey("PendingEmailAddressProfileId");
                                });

                            b1.Navigation("EmailAddress")
                                .IsRequired();
                        });

                    b.OwnsOne("Auth.Domain.ValueObjects.PersonName", "PersonName", b1 =>
                        {
                            b1.Property<Guid>("ProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PersonName");

                            b1.HasKey("ProfileId");

                            b1.ToTable("Profile");

                            b1.WithOwner()
                                .HasForeignKey("ProfileId");
                        });

                    b.Navigation("EmailAddress")
                        .IsRequired();

                    b.Navigation("PendingEmailAddress");

                    b.Navigation("PersonName")
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Auth.Domain.Entities.Authorization", null)
                        .WithMany("RolePermissions")
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Aggregates.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Entities.ScopePermission", b =>
                {
                    b.HasOne("Auth.Domain.Entities.Authorization", null)
                        .WithMany("ScopePermissions")
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Auth.Domain.Aggregates.Scope", null)
                        .WithMany()
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.Role", b =>
                {
                    b.Navigation("Entitlements");
                });

            modelBuilder.Entity("Auth.Domain.Aggregates.User", b =>
                {
                    b.Navigation("Authentication")
                        .IsRequired();

                    b.Navigation("Authorization")
                        .IsRequired();

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("Auth.Domain.Entities.Authorization", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("ScopePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
