version: "3.9"

services:
  auth_database:
    container_name: auth_database
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    volumes:
        - ./Data/AuthDatabase:/var/opt/mssql/data
    ports:
      - 5001:1433
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HHHHhhhh1111"
    networks:
      - application

  otp_database:
    container_name: otp_database
    image: postgres:16
    environment:
      POSTGRES_DB: Otp
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: HHHHhhhh1111
    ports:
      - "5002:5432"
    volumes:
      - ./Data/OtpDatabase:/var/lib/postgresql/data
    networks:
      - application
      
  notification_database:
    container_name: notification_database
    image: postgres:16
    environment:
      POSTGRES_DB: Notification
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: HHHHhhhh1111
    ports:
      - "5003:5432"
    volumes:
      - ./Data/NotificationDatabase:/var/lib/postgresql/data
    networks:
      - application

  auth_scheduler:
    container_name: auth_scheduler
    image: postgres:16
    environment:
      POSTGRES_DB: Scheduler
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: HHHHhhhh1111
    ports:
      - "5004:5432"
    volumes:
      - ./Data/AuthScheduler:/var/lib/postgresql/data
    networks:
      - application

  otp_scheduler:
    container_name: otp_scheduler
    image: postgres:16
    environment:
      POSTGRES_DB: Scheduler
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: HHHHhhhh1111
    ports:
      - "5005:5432"
    volumes:
      - ./Data/OtpScheduler:/var/lib/postgresql/data
    networks:
      - application
      
  notification_scheduler:
    container_name: notification_scheduler
    image: postgres:16
    environment:
      POSTGRES_DB: Scheduler
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: HHHHhhhh1111
    ports:
      - "5006:5432"
    volumes:
      - ./Data/NotificationScheduler:/var/lib/postgresql/data
    networks:
      - application
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4-management
    hostname: rabbitmq
    restart: always
    volumes:
      - ./Data/RabbitMQ:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=mquser
      - RABBITMQ_DEFAULT_PASS=HHHHhhhh1111
    networks:
      - application
 
  vault:
    image: hashicorp/vault:1.20.1
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./Data/Vault:/vault/file
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK


  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
        - 5000:8080
    networks:
        - application
   
networks:
  application:
    driver: bridge